In [9]:
import numpy as np
import random

**1** Cree una matriz de números aleatorios de tamaño 9x9. Cada número debe ser una potencia aleatoria de 2 (2 N), en el rango entre 1 y N, donde N es un número ingresado por el usuario. Luego haga lo siguiente:
a. Cree la sub-matriz B, a partir de la fila 5 hasta la fila 9 y la columna 1 hasta la
columna 4.
b. Encuentre el promedio (media) de la diagonal principal de A.
c. Encuentre el promedio de la segunda columna de B.
d. Encuentre el promedio y el valor mayor de A y súmelos, luego haga lo mismo con B. Después compare e imprima cual de los dos resultados es mayor

In [18]:
def random_gen(N):
    random_array = np.zeros((9,9))
    for i in range(len(random_array)):
        exp = random.randint(1,N)
        random_array[i] = 2**exp
    
    return random_array

matrix = random_gen(10)

#Punto A

B_matrix = matrix[4:9, 0:4]
print(matrix, '\n\n\n', B_matrix)

[[  16.   16.   16.   16.   16.   16.   16.   16.   16.]
 [1024. 1024. 1024. 1024. 1024. 1024. 1024. 1024. 1024.]
 [ 256.  256.  256.  256.  256.  256.  256.  256.  256.]
 [ 256.  256.  256.  256.  256.  256.  256.  256.  256.]
 [1024. 1024. 1024. 1024. 1024. 1024. 1024. 1024. 1024.]
 [   8.    8.    8.    8.    8.    8.    8.    8.    8.]
 [  64.   64.   64.   64.   64.   64.   64.   64.   64.]
 [   4.    4.    4.    4.    4.    4.    4.    4.    4.]
 [   8.    8.    8.    8.    8.    8.    8.    8.    8.]] 


 [[1024. 1024. 1024. 1024.]
 [   8.    8.    8.    8.]
 [  64.   64.   64.   64.]
 [   4.    4.    4.    4.]
 [   8.    8.    8.    8.]]


In [37]:
#Punto B Y C

print(' A:', (matrix.diagonal()).mean(), '\n\n', 'B:',B_matrix[:,1].mean())

 A: 295.55555555555554 

 B: 221.6


In [39]:
#Punto D

sum_A, sum_B = matrix.max() + matrix.mean(), B_matrix.max() + B_matrix.mean()

if sum_A < sum_B:
    print(f'{sum_B} B es el mayor')

else:
    print(f'{sum_A} A es el mayor')

1319.5555555555557 A es el mayor


**2** Haga un algoritmo que permita generar una matriz de dimensiones aleatorias
(mínimo de 2x2 y máximo de 6x6), y que contenga valores aleatorios enteros
(con el rango que usted desee). Pregunte al usuario por un valor N (en el
mismo rango mencionado) y luego imprima:
a) Las posiciones y valores de la matriz que sean iguales a N
b) Las posiciones y valores que sean menores a N.
c) Las posiciones y valores que sean mayores a N.

In [81]:
def random_matrix(max_number_range, N):
    rand = random.randint(0, max_number_range)
    matrix = np.zeros((rand, rand))
    for i in range(len(matrix)):
        matrix[i] = random.randint(0, max_number_range)
    
    equal_N = [np.where(matrix == N), matrix[np.where(matrix == N)]]
    minor_N = [np.where(matrix <= N), matrix[np.where(matrix <= N)]]
    major_N = [np.where(matrix >= N), matrix[np.where(matrix >= N)]]
    
    print('= N (Pocisiones, Valores)\n\n',equal_N[0],'\n\n<= N (Pocisiones, Valores)\n\n',minor_N[0],'\n\n=> N (Pocisiones, Valores)\n\n',major_N[0])

random_matrix(10, 7)

= N (Pocisiones, Valores)

 (array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8], dtype=int64), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)) 

<= N (Pocisiones, Valores)

 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8], dtype=int64), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
       6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)) 

=> N (Pocisiones, Valores)

 (array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6,

**3** Cree una matriz A de valores aleatorios tipo float entre 0 y 20 y de orden 5x5, y
una matriz B de orden 10x10 a partir de los siguientes componentes (en el
mismo orden):

 | A | 2A |
|----------|----------|
| A^2    | A+2   |

 
Nota: A
2 denota la multiplicación de los elementos de A con A, componente a
componente, es decir, NO coincide con la multiplicación definida en el álgebra lineal.

In [98]:
A = np.random.uniform(0,20, size=(5,5))
B = np.zeros((10,10))
B[0:5, 0:5] = A
B[0:5, 5:10] = 2*A
B[5:10, 0:5] = A*A
B[5:10, 5:10] = A+2

array([[2.11099427e+00, 6.51274139e-01, 2.17922935e+00, 1.88060952e+00,
        2.20151304e+00, 4.22198855e+00, 1.30254828e+00, 4.35845871e+00,
        3.76121903e+00, 4.40302609e+00],
       [3.42468049e+00, 1.26795972e+01, 3.84430502e-01, 1.54828739e+01,
        1.59043172e+01, 6.84936099e+00, 2.53591944e+01, 7.68861003e-01,
        3.09657478e+01, 3.18086345e+01],
       [1.08950529e+01, 1.26778359e+01, 1.25038839e+01, 1.65809574e+01,
        1.23160359e+01, 2.17901058e+01, 2.53556719e+01, 2.50077678e+01,
        3.31619148e+01, 2.46320719e+01],
       [4.77785598e+00, 1.20867179e+01, 8.73292727e+00, 1.72533591e+01,
        1.88345009e+01, 9.55571195e+00, 2.41734358e+01, 1.74658545e+01,
        3.45067182e+01, 3.76690017e+01],
       [2.12594150e+00, 1.85913091e+01, 8.97453587e+00, 5.91086738e+00,
        2.30612102e-01, 4.25188300e+00, 3.71826181e+01, 1.79490717e+01,
        1.18217348e+01, 4.61224205e-01],
       [4.45629682e+00, 4.24158004e-01, 4.74904058e+00, 3.53669216e+00,
   